// <auto-generated />
using System;
using E_Commerse_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerse_Website.Migrations
{
    [DbContext(typeof(myContext))]
    [Migration("20241204161215_sliderandsection")]
    partial class sliderandsection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerse_Website.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<string>("admin_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.ToTable("tbl_admin");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.AdminHistory", b =>
                {
                    b.Property<int>("AH_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AH_id"));

                    b.Property<bool>("AH_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("AH_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AH_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("AH_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("admin_id")
                        .HasColumnType("int");

                    b.HasKey("AH_id");

                    b.HasIndex("admin_id");

                    b.ToTable("tbl_adminHistory");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Cart", b =>
                {
                    b.Property<int>("cart_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cart_id"));

                    b.Property<int>("cart_status")
                        .HasColumnType("int");

                    b.Property<int>("cust_id")
                        .HasColumnType("int");

                    b.Property<int>("prod_id")
                        .HasColumnType("int");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.HasKey("cart_id");

                    b.HasIndex("prod_id");

                    b.ToTable("tbl_cart");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_id"));

                    b.Property<bool>("category_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("category_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_id");

                    b.ToTable("tbl_category");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_id"));

                    b.Property<string>("customer_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isVerified")
                        .HasColumnType("bit");

                    b.HasKey("customer_id");

                    b.ToTable("tbl_customer");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Faqs", b =>
                {
                    b.Property<int>("faq_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("faq_id"));

                    b.Property<string>("faq_answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faq_question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("faq_id");

                    b.ToTable("tbl_faqs");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Feedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feedback_id"));

                    b.Property<string>("feedback_message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("feedback_id");

                    b.ToTable("tbl_feedback");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.OTP_Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("tbl_OTP_Customer");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"));

                    b.Property<int>("adm_id")
                        .HasColumnType("int");

                    b.Property<int>("cat_id")
                        .HasColumnType("int");

                    b.Property<bool>("product_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("product_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("product_price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("product_id");

                    b.HasIndex("adm_id");

                    b.HasIndex("cat_id");

                    b.ToTable("tbl_product");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Section", b =>
                {
                    b.Property<int>("section_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("section_id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("section_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("section_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("section_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_time")
                        .HasColumnType("datetime2");

                    b.HasKey("section_id");

                    b.ToTable("tbl_Section");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.SectionProduct", b =>
                {
                    b.Property<int>("section_product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("section_product_id"));

                    b.Property<bool>("is_visible")
                        .HasColumnType("bit");

                    b.Property<int>("prod_id")
                        .HasColumnType("int");

                    b.Property<int>("section_id")
                        .HasColumnType("int");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.HasKey("section_product_id");

                    b.HasIndex("prod_id");

                    b.HasIndex("section_id");

                    b.ToTable("tbl_SectionProduct");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Slider", b =>
                {
                    b.Property<int>("slider_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slider_id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("slider_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("slider_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slider_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_time")
                        .HasColumnType("datetime2");

                    b.HasKey("slider_id");

                    b.ToTable("tbl_Slider");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.SliderProduct", b =>
                {
                    b.Property<int>("slider_product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slider_product_id"));

                    b.Property<bool>("is_visible")
                        .HasColumnType("bit");

                    b.Property<int>("prod_id")
                        .HasColumnType("int");

                    b.Property<string>("product_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("slider_id")
                        .HasColumnType("int");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.HasKey("slider_product_id");

                    b.HasIndex("prod_id");

                    b.HasIndex("slider_id");

                    b.ToTable("tbl_SliderProduct");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.AdminHistory", b =>
                {
                    b.HasOne("E_Commerse_Website.Models.Admin", "Admin")
                        .WithMany("History")
                        .HasForeignKey("admin_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Cart", b =>
                {
                    b.HasOne("E_Commerse_Website.Models.Product", "prod")
                        .WithMany()
                        .HasForeignKey("prod_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("prod");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.OTP_Customer", b =>
                {
                    b.HasOne("E_Commerse_Website.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Product", b =>
                {
                    b.HasOne("E_Commerse_Website.Models.Admin", "Admin")
                        .WithMany("Product")
                        .HasForeignKey("adm_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerse_Website.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.SectionProduct", b =>
                {
                    b.HasOne("E_Commerse_Website.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("prod_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerse_Website.Models.Section", "Section")
                        .WithMany("SectionProducts")
                        .HasForeignKey("section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.SliderProduct", b =>
                {
                    b.HasOne("E_Commerse_Website.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("prod_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerse_Website.Models.Slider", "Slider")
                        .WithMany("SliderProducts")
                        .HasForeignKey("slider_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Slider");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Admin", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Section", b =>
                {
                    b.Navigation("SectionProducts");
                });

            modelBuilder.Entity("E_Commerse_Website.Models.Slider", b =>
                {
                    b.Navigation("SliderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
